# Generated by Django 4.1 on 2022-09-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="category",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
