# Generated by Django 4.1 on 2022-09-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_image_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Processing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(default="none", max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name="image",
            name="category",
            field=models.CharField(default="none", max_length=32),
        ),
    ]
