# Generated by Django 4.1 on 2022-09-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_type_processing_type1_remove_image_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processing",
            name="c",
            field=models.CharField(default="5", max_length=32),
        ),
        migrations.AddField(
            model_name="processing",
            name="k",
            field=models.CharField(default="0.2", max_length=32),
        ),
        migrations.AddField(
            model_name="processing",
            name="kernel",
            field=models.CharField(default="15", max_length=32),
        ),
        migrations.AddField(
            model_name="processing",
            name="thresh",
            field=models.CharField(default="127", max_length=32),
        ),
    ]
