# Generated by Django 4.1 on 2022-09-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_processing_c_processing_k_processing_kernel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(default="0", max_length=32),
        ),
    ]
