# Generated by Django 4.1 on 2022-09-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_image_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="type",
            field=models.CharField(default="0", max_length=32),
        ),
        migrations.AlterField(
            model_name="image", name="title", field=models.CharField(max_length=32),
        ),
    ]
